### PR TITLE
Making some modifications to the way in which plans and protocols are…

### PR DESCRIPTION
**Pull request by cereallarceny**
Basically we're trying to switch the workers to a "multiple plans" and "multiple protocols" workflow, instead of being locked into one specific training plan and one optional protocol for the time being.

Currently, our list of unknowns and unsolved questions open for discussion are:
- [ ] How do we wire the outputs of a plan/protocol to the inputs of another plan, protocol, or report?

### CODE REVIEW

**Comment by iamtrask** [comment]
@karlhigley @LaRiffle - If everything's a plan/protocol, would this new perspective require Plans to be able to (internally) represent "if statements" and "for loops"? Do we think this is possible?

**Comment by karlhigley** [comment]
Torchscript can do for loops (normally via `script` and unrolled via `trace`) and if statements (but only in `script` mode.) So, the support for those exists in the underlying substrate we’d use on mobile, but I have no idea how we’d do it on web.

**Comment by iamtrask** [comment]
How about for Protocols? They're static graphs, no?

**Comment by karlhigley** [comment]
Thus far, I haven’t seen an example of something that we’d need if statements for in the middle of a train/evaluate process. Where is my imagination failing me on that?

**Comment by iamtrask** [comment]
well, if EVERYTHING is a plan/protocol in the entire training process on device, then there's the main for loop

for batch in trainign_data:

**Comment by karlhigley** [comment]
Protocols are anticipated to be static graphs, yes. (So is any Torchscript generated by JIT `trace`.)

**Comment by iamtrask** [comment]
Sure - but that was when we were assuming the client would call such plans and protocols within it's own local for loops

**Comment by karlhigley** [comment]
I thought feeding batches was outside the scope of Plans? I heard we were going to run a single Plan once for each training batch on a worker, yeah?

**Comment by iamtrask** [comment]
That's what I heard too - but @cereallarceny just mentioned that if we can stitch plans and protocols together end to end automatically, then we won't have any for loops on devicee... i.e. the worker logic looks like

```
import syft from 'syft.js';
import tf from '@tensorflow/tfjs';
const worker = new syft({
  url: 'https://localhost:3000'
});
// You may set up multiple jobs.
const job = worker.newJob({
  model: 'my-federated-model',
  version: '0.1.0'  // If omitted, PyGrid will assume it's the latest version
});
job.start(myData);
```

**Comment by karlhigley** [comment]
Okay, cool. So then the question is: do we need to put the for loop inside the Plan/Protocol, or just the body of the for loop and leave iteration to the executor?

**Comment by iamtrask** [comment]
Great question

**Comment by cereallarceny** [comment]
The code example that you posted @iamtrask is a bit far off. Can we stay on topic of the PR guys? We're venturing into futureland...

**Comment by iamtrask** [comment]
> The code example that you posted @iamtrask is a bit far off. Can we stay on topic of the PR guys? We're venturing into futureland...

Agreed - as far as this PR is concerned - i'm quite happy

**Comment by cereallarceny** [comment]
Closing this PR as it's misunderstood and off-topic from the contents of the PR.

**Pull request closed without merging**
