### PR TITLE
Adding an authentication plan

### PR DESCRIPTION
**Pull request by cereallarceny**

### CODE REVIEW

**Comment by cereallarceny** [comment]
1. I'm going to investigate this @vvmnnnkv.
2. I hear what you're saying, but I think that's overkill for now. We can easily add such functionality down the line, but a simple "supply your own function that takes an `auth_token` and returns a boolean" is way easier.
3. I think you're right. I'll change it to "authentication".

**Comment by cereallarceny** [comment]
I've removed any references to plans and instead decided to go with JWT verification. In this model, the following flow happens:

1. A worker requests to their API for a JWT to be created, passing with it some sort of identifying information (like a user ID or whatever).
2. The API creates a JWT for that user and returns it back to the worker.
3. The worker forwards this newly received `auth_token` to PyGrid.
4. PyGrid receives the `auth_token` from the worker and passes this to the JTW verification API endpoint supplied in the `server_config`.
5. The API verifies that token in the system and determines whether or not it's valid.
6. PyGrid receives a "valid" or "invalid" response from the API and issues a `worker_id` given a valid response or returns an error given an invalid response.

**Comment by vvmnnnkv** [comment]
1. In this flow, token doesn't have to be JWT because pygrid never looks inside of it anyway, it can be any opaque token.
2. But if it's JWT, pygrid could take advantage of this, by validating JWT signature on its own to avoid making API call. In this case, `server_config` could contain the secret passphrase instead of API endpoint. PyGrid would validate JWT is signed with the same passphrase. This would allow having some auth enabled w/o having additional API at all (e.g. JWT tokens can be generated offline and hardcoded in workers). The downside is that such tokens will be hard to invalidate, so it's only for simple cases.

**Comment by cereallarceny** [comment]
Totally correct @vvmnnnkv, I'll change the documentation now. I think that should be good enough.

**Comment by cereallarceny** [comment]
Here's what I'm thinking for authentication:

1. The worker makes a request for a JWT token to be created at `https://api.example.com/request-token`. The worker passes their user_id (or some sort of unique identifier of their login state in their app logic) to this endpoint to be embedded in the payload.
2. The endpoint puts that payload inside the JWT token after base64 encoding it, and also supplies a 256-bit secret key which may also optionally be base64 encoded. The resulting JWT is returned to the worker.
3. The worker receives their token and sends it to PyGrid for authentication.
4. PyGrid receives the token and does two things. First, PyGrid compares the 256-bit secret that it’s been given in the server_config to check if it’s the same 256-bit secret token used to generate the key at the /request-token endpoint. If it is the same secret, the whole token is passed to https://api.example.com/verify-token where both the secret AND the payload are verified. This is also important because if a worker figures out the 256-bit secret used to sign the token, they could say they are whoever they are. This allows for a second validation that proves that the worker is who they say they are.
5. Upon a positive result from the /verify-token endpoint, a worker ID is issued to the worker and the process continues, otherwise, an error is thrown.

I think it’s good to verify the secret of the API on PyGrid. Definitely a good idea, but the PyGrid also needs to allow the user auth API to verify that the worker is who they say they are. Otherwise, they could generate any JWT token they want if the payload doesn’t match the token. :slightly_smiling_face:

These tokens would perhaps be stored in the user auth API database as:

```json
{
  "token": "skdjfhskdjhf.sdkfhskjdeseeeeehf.chbjcjegjyse,
  "user_id": 1239847973
}
```

**Pull request merged**
